### ISSUE TITLE
pip install does not resolve all dependencies

### ISSUE THREAD

**Issue by pavel-kolesnikov** [mdellweg/pass_secret_service#27]
Hi, I've installed `pass_secret_service` with `pip install pass_secret_service` on Fedora 35 with default python.

Direct invocation gives this:
```
[pk@pkolesnikov-f34 ~]$ pass_secret_service 
Traceback (most recent call last):
  File "/home/pk/.local/bin/pass_secret_service", line 5, in <module>
    from pass_secret_service import main
  File "/home/pk/.local/lib/python3.10/site-packages/pass_secret_service/__init__.py", line 1, in <module>
    from pass_secret_service.pass_secret_service import main
  File "/home/pk/.local/lib/python3.10/site-packages/pass_secret_service/pass_secret_service.py", line 8, in <module>
    from pass_secret_service.interfaces.service import Service
  File "/home/pk/.local/lib/python3.10/site-packages/pass_secret_service/interfaces/service.py", line 11, in <module>
    from pass_secret_service.interfaces.session import Session
  File "/home/pk/.local/lib/python3.10/site-packages/pass_secret_service/interfaces/session.py", line 8, in <module>
    from cryptography.utils import int_from_bytes
ModuleNotFoundError: No module named 'cryptography'
```

**Comment by 3nprob** [comment]
This seems to just be a matter of the release on pypi being out of date. This issue does not appear on current `develop` branch. (Running `pip install -r requirements.txt` inside `fedora:latest` docker image.
